### ISSUE TITLE
add debate as a subclass of chain

### ISSUE THREAD

**Issue by josh-ashkinaze** [josh-ashkinaze/plurals#15]
Here is what I am thinking:

Debate should be Chain except two differences:
1. We only allow two agents
2. We format responses like "You: blah", "other; blah" 

Didn't test it but I think code would be as simple as:

```
class Debate(Chain):
    def __init__(self, agents: List[Agent], task_description: Optional[str] = None, shuffle: bool = False, cycles: int = 1, last_n: int = 1, combination_instructions: Optional[str] = "default", moderator: Optional[Moderator] = None):
        if len(agents) != 2:
            raise ValueError("Debate requires exactly two agents.")
        super().__init__(agents, task_description, shuffle, cycles, last_n, combination_instructions, moderator)

    def format_previous_responses(self, responses: List[str]) -> str:
        """
        Format the previous responses for a debate-like interaction.
        Alternates between "You:" and "Other:" for each response in the list.
        """
        formatted_responses = []
        for i, response in enumerate(responses):
            prefix = "You:" if i % 2 == 0 else "Other:"
            formatted_responses.append(f"{prefix} {response}\n")
        return "".join(formatted_responses)

```

**Comment by josh-ashkinaze** [comment]
Hmmmm just realized potential issue with my implementation. This formatting can work I believe but I think for the moderator we need to have different labels than YOU and OTHER. 

So the implementation would actually be

1. Override `foramt_previous_responses' as we do here. Add an arg to `format_previous_responses' called 'who' and this can either be `agent' or `moderator'. When we call it with `agent' it does this `You' and `Other' thing. When we call it with `moderator' it says `Conversation Partner 1` and `Conversation Partner 2` in place of `you` and `other'

2. Override `process_chain' so that agents and moderator use the appropriate formatting. You just want to pass in the `who` arg for each.

**Comment by efry0** [comment]
Working on it!

**Comment by josh-ashkinaze** [comment]
Oh haha I didn't even necesarily mean for this week but great!
