### ISSUE TITLE
Improve parallel requests handling 

### ISSUE THREAD

**Issue by josh-ashkinaze** [josh-ashkinaze/plurals#30]
In the implementation I have, I am sending parallel LiteLLM completion requests through Native Python libraries. But some providers have these _super low_ rate limits. 

So I see a few paths forward and I am wondering if you can explore this for next week:

Q1: First, is it the case that LiteLLM's batch completion endpoint handles rate limit errors? 

If the answer to Q1 is Yes:
- Task: Try to switch our current implementation to simply use batch completion. 

If the answer to Q1 is No:
I don't think it's worth re-factoring to that since it would have no benefit. Instead, there are some low-lying options:

Experiment: What if we just set a high `num_retries` as the default for `kwargs` for Ensemble? `num_retries` is LiteLLM using Tenacity to wait on rate limit errors. 

Propose/implement on `development`: If you find it still has problems then just make a proposal for our own waiting scheme using tenacity itself (the library litellm is using to wait on requests)

**Comment by narenedara** [comment]
Was looking into this and I don't think batch completion handles rate limit
errors. I am going to try complete the NO solution but I was wondering how
I would be able to test it. Would I just make multiple requests in a row or
is there a better way to do it?

**Comment by josh-ashkinaze** [comment]
after implementing add mocking unit test that makes sure if LiteLLM throws a RateLimitError we catch it and tell user to increase max_retries

**Comment by josh-ashkinaze** [comment]
Okay based on our meeting:
- Do parallel requests outside of our system with `num_retries` high
- Post issue in LiteLLM repository since it seems their `num_retries` is behaving unexpected
