### ISSUE TITLE
more templates for outputs [focus group, creativity]

### ISSUE THREAD

**Issue by josh-ashkinaze** [josh-ashkinaze/plurals#33]
I am wondering----can you create some more templates? Here are two that I think we should add.

**Focus Group**
Remember how I sent you the code for our human experiments I ran? I think that should be a pre-defined template actually. So for personas, we want a persona that tells individuals to respond as if they are in a focus group based on their own personal experiences (see exact language from the experiment). 

**Creativity**
We sort of have this but I really want a simple one for moderators around divergent thinking. Let's use some of their language in our template and document a citation in the Yaml to give credit (cite this pre-print in APA format). 
https://arxiv.org/abs/2305.19118

**Comment by efry0** [comment]
Please clarify - should we make changes to instructions.yaml file ( new personas - 'focus-group', 'creative' and Moderator class ( to be able replacing new variables - brand category, etc.) or is it just for the demo template without yaml files changes?

**Comment by josh-ashkinaze** [comment]
I mean change the instructions.yaml on a new branch called
dev/add-more-templates

Best,
Josh

**Comment by efry0** [comment]
To use new placeholders, I will have to change moderator class. Should I do
that on the dev/add-more-templates branch as well?

**Comment by josh-ashkinaze** [comment]
Why would the moderator class change? Can we just make it new template for combination instructions?

**Comment by efry0** [comment]
I thought maybe we will need to change this:

format(
task=original_task,
previous_responses=combined_responses_str,
persona=self.persona)

to add other placeholders- like you have in your example for focus-group -
{domain}, {brand-development}, but maybe don't need it with the SmartString

**Comment by josh-ashkinaze** [comment]
I just used persona tbh
